export const WORDS = [
  // Technologie & Internet
  'Laptop', 'Smartphone', 'Browser', 'Cloud', 'Datenbank', 'Server', 'Router', 'Modem', 'WiFi',
  'Bluetooth', 'USB', 'RAM', 'CPU', 'GPU', 'Festplatte', 'SSD', 'Monitor', 'Tastatur', 'Maus',
  'Webcam', 'Mikrofon', 'Drucker', 'Scanner', 'Backup', 'Passwort', 'Firewall', 'VPN', 'Antivirus',
  'Update', 'Download', 'Upload', 'Streaming', 'Cache', 'Cookie', 'Plugin', 'App', 'Website',
  'Email', 'Forum', 'Chat', 'Messenger', 'Video-Anruf', 'Zoom', 'Login', 'Logout', 'Account',

  // Alltag
  'Tasse', 'Teller', 'Gabel', 'Messer', 'Löffel', 'Glas', 'Flasche', 'Topf', 'Pfanne', 'Ofen',
  'Kühlschrank', 'Mikrowelle', 'Spüle', 'Handtuch', 'Zahnbürste', 'Shampoo', 'Seife', 'Dusche',
  'Badewanne', 'Toilette', 'Spiegel', 'Bürste', 'Kamm', 'Fön', 'Rasierer', 'Zahn', 'Lippen',
  'Augen', 'Haare', 'Haut', 'Nägel', 'Tür', 'Fenster', 'Vorhang', 'Gardine', 'Teppich', 'Matte',
  'Kerze', 'Licht', 'Lampe', 'Glühbirne', 'Schalter', 'Stecker', 'Kabel', 'Batterie', 'Akku',

  // Essen & Getränke
  'Pizza', 'Burger', 'Pasta', 'Salat', 'Suppe', 'Steak', 'Hähnchen', 'Fisch', 'Kartoffel',
  'Reis', 'Brot', 'Butter', 'Käse', 'Milch', 'Joghurt', 'Ei', 'Speck', 'Wurst', 'Schinken',
  'Tomate', 'Gurke', 'Zwiebel', 'Knoblauch', 'Paprika', 'Karotte', 'Brokkoli', 'Spinat', 'Salat',
  'Apfel', 'Banane', 'Orange', 'Zitrone', 'Erdbeere', 'Himbeere', 'Kirsche', 'Traube', 'Melone',
  'Kaffee', 'Tee', 'Saft', 'Wasser', 'Bier', 'Wein', 'Whiskey', 'Vodka', 'Rum', 'Gin',
  'Schnaps', 'Soda', 'Limonade', 'Smoothie', 'Milchshake', 'Kakao', 'Punsch', 'Cocktail',

  // Natur & Tiere
  'Baum', 'Blume', 'Rose', 'Tulpe', 'Gänseblümchen', 'Löwenzahn', 'Kaktus', 'Sukkulente',
  'Gras', 'Kraut', 'Strauch', 'Hecke', 'Wald', 'Wiese', 'Feld', 'Berg', 'Tal', 'Fluss',
  'See', 'Meer', 'Ozean', 'Strand', 'Insel', 'Bucht', 'Hafen', 'Brücke', 'Schlucht',
  'Löwe', 'Tiger', 'Leopard', 'Bär', 'Wolf', 'Fuchs', 'Hirsch', 'Reh', 'Schaf', 'Ziege',
  'Pferd', 'Esel', 'Kuh', 'Schwein', 'Schwein', 'Huhn', 'Gans', 'Ente', 'Katze', 'Hund',
  'Kaninchen', 'Hamster', 'Maus', 'Ratte', 'Vogel', 'Adler', 'Falke', 'Eule', 'Krähe', 'Taube',
  'Pinguin', 'Papagei', 'Kolibri', 'Fisch', 'Hai', 'Delphin', 'Wal', 'Schlange', 'Krokodil',
  'Frosch', 'Schildkröte', 'Insekt', 'Biene', 'Wespe', 'Fliege', 'Mücke', 'Käfer', 'Regenwurm',

  // Berufe & Rollen
  'Arzt', 'Krankenschwester', 'Zahnarzt', 'Apotheker', 'Therapist', 'Psychiater', 'Chirurg',
  'Lehrer', 'Professor', 'Schulrektor', 'Bibliothekar', 'Erzieher', 'Kindergärtner', 'Trainer',
  'Polizist', 'Detektiv', 'Anwalt', 'Richter', 'Staatsanwalt', 'Notar', 'Schiedsrichter',
  'Feuerwehrmann', 'Rettungssanitäter', 'Pilot', 'Stewardess', 'Kapitän', 'Matrose', 'Navigator',
  'Ingenieur', 'Architekt', 'Programmierer', 'Graphiker', 'Designer', 'Fotograf', 'Kameramann',
  'Schauspieler', 'Regisseur', 'Drehbuchautor', 'Produzent', 'Komponist', 'Musiker', 'Sänger',
  'Maler', 'Bildhauer', 'Kunsthandwerker', 'Schriftsteller', 'Journalist', 'Redakteur', 'Blogger',
  'Koch', 'Kellner', 'Barkeeper', 'Bäcker', 'Metzger', 'Gemüsehändler', 'Florist',
  'Friseur', 'Barbier', 'Kosmetiker', 'Masseur', 'Fitnesstrainer', 'Sportler', 'Schiedsrichter',
  'Bauer', 'Gärtner', 'Imker', 'Fischer', 'Jäger', 'Förster', 'Landwirt',
  'Klempner', 'Elektriker', 'Schreiner', 'Maurer', 'Dachdecker', 'Maler', 'Metallarbeiter',
  'Taxifahrer', 'Busfahrer', 'Zugführer', 'Lkw-Fahrer', 'Lieferfahrer', 'Postbote', 'Kurier',

  // Orte
  'Zuhause', 'Wohnung', 'Haus', 'Villa', 'Hütte', 'Schloss', 'Turm', 'Kirche', 'Moschee',
  'Tempel', 'Synagoge', 'Kloster', 'Schule', 'Universität', 'Schulhof', 'Klassenzimmer',
  'Büro', 'Konferenzzimmer', 'Lagerhaus', 'Fabrik', 'Werkstatt', 'Labor', 'Krankenhaus',
  'Apotheke', 'Zahnarzt', 'Friseursalon', 'Fitness-Studio', 'Yoga-Studio', 'Fitnessstudio',
  'Restaurant', 'Café', 'Kneipe', 'Bar', 'Pub', 'Diskothek', 'Club', 'Nachtclub',
  'Supermarkt', 'Markt', 'Geschäft', 'Laden', 'Einkaufszentrum', 'Mall', 'Boutique',
  'Bank', 'Geldautomat', 'Postamt', 'Bücherei', 'Bibliothek', 'Museum', 'Galerie', 'Theater',
  'Kino', 'Konzertsaal', 'Opern', 'Zoo', 'Aquarium', 'Freizeitpark', 'Karussell', 'Achterbahn',
  'Park', 'Spielplatz', 'Fußballplatz', 'Tennisplatz', 'Schwimmbad', 'Strandbar', 'Sauna',
  'Flughafen', 'Bahnhof', 'Bushaltestelle', 'Taxi-Stand', 'Autobahnraststätte', 'Tankstelle',
  'Straße', 'Allee', 'Gasse', 'Platz', 'Boulevard', 'Autobahn', 'Schnellstraße', 'Bundesstraße',
  'Brücke', 'Tunnel', 'Kreuzung', 'Kreisverkehr', 'Zebrastreifen', 'Ampel', 'Verkehrsschild',
  'Wald', 'Wiese', 'Garten', 'Park', 'Grünfläche', 'Friedhof', 'Sportplatz', 'Übungsplatz',

  // Sportarten
  'Fußball', 'Basketball', 'Tennis', 'Badminton', 'Volleyball', 'Handball', 'Eishockey',
  'American Football', 'Baseball', 'Cricket', 'Rugby', 'Golf', 'Bowling', 'Billard',
  'Boxen', 'Wrestling', 'Karate', 'Judo', 'Kung Fu', 'Taekwondo', 'Fechten',
  'Schwimmen', 'Tauchen', 'Surfen', 'Kitesurfen', 'Windsurfen', 'Segeln', 'Rudern',
  'Klettern', 'Bergsteigen', 'Wandern', 'Trekking', 'Radfahren', 'Mountainbiken', 'BMX',
  'Skateboarden', 'Rollschuhlaufen', 'Eislaufen', 'Eishockey', 'Skifahren', 'Snowboardfahren',
  'Reiten', 'Springreiten', 'Dressur', 'Langlauf', 'Biathlon', 'Triathlon', 'Ironman',
  'Joggen', 'Sprinten', 'Leichtathletik', 'Hochsprung', 'Weitsprung', 'Stabhochsprung',
  'Kunstturnen', 'Trampolinspringen', 'Rhythmische Sportgymnastik', 'Eiskunstlauf',
  'Curling', 'Schach', 'Poker', 'Dart', 'Tischtennis', 'Squash', 'Badminton',

  // Fahrzeuge
  'Auto', 'Laster', 'Bus', 'Zug', 'U-Bahn', 'Straßenbahn', 'Fahrrad', 'Motorrad',
  'Roller', 'Tretroller', 'Skateboard', 'Rollschuhe', 'Inline-Skates', 'Flugzeug',
  'Hubschrauber', 'Drohne', 'Segelflugzeug', 'Propellerflugzeug', 'Jet', 'Raumschiff',
  'Schiff', 'Segelboot', 'Motorboot', 'Kanu', 'Kajak', 'Surfbrett', 'Jetski',
  'Eisenbahn', 'Straßenbahn', 'S-Bahn', 'Hochbahn', 'Einsatzfahrzeug', 'Krankenwagen',
  'Feuerwehr', 'Polizeiauto', 'Panzer', 'Hubschrauber', 'Flugzeugträger', 'U-Boot',

  // Länder & Städte
  'Deutschland', 'Frankreich', 'Spanien', 'Italien', 'Vereinigtes Königreich', 'Irland',
  'Schweiz', 'Österreich', 'Polen', 'Tschechien', 'Ungarn', 'Rumänien', 'Bulgarien',
  'Griechenland', 'Portugal', 'Norwegen', 'Schweden', 'Finnland', 'Dänemark', 'Niederlande',
  'Belgien', 'Luxemburg', 'Frankreich', 'Liechtenstein', 'Island', 'Malta', 'Zypern',
  'Russland', 'Ukraine', 'Belarus', 'Moldau', 'Litauen', 'Lettland', 'Estland',
  'USA', 'Kanada', 'Mexiko', 'Brasilien', 'Argentinien', 'Chile', 'Peru', 'Kolumbien',
  'Australien', 'Neuseeland', 'Fiji', 'Samoa', 'Tonga', 'Vanuatu', 'Palau',
  'Ägypten', 'Südafrika', 'Nigeria', 'Kenia', 'Tansania', 'Uganda', 'Ghana', 'Senegal',
  'Marokko', 'Tunesien', 'Algerien', 'Äthiopien', 'Somalia', 'Sudan', 'Libyen',
  'Japan', 'China', 'Indien', 'Thailand', 'Vietnam', 'Kambodscha', 'Laos', 'Singapur',
  'Malaysia', 'Indonesien', 'Philippinen', 'Südkorea', 'Nordkorea', 'Mongolei', 'Myanmar',
  'Pakistan', 'Bangladesch', 'Sri Lanka', 'Nepal', 'Bhutan', 'Afghanistan', 'Irak', 'Iran',
  'Saudi-Arabien', 'Israel', 'Vereinigte Arabische Emirate', 'Katar', 'Bahrain', 'Kuwait',

  'Berlin', 'München', 'Hamburg', 'Köln', 'Frankfurt', 'Düsseldorf', 'Dortmund', 'Essen',
  'Leipzig', 'Dresden', 'Hannover', 'Nürnberg', 'Augsburg', 'Stuttgart', 'Mannheim',
  'Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Straßburg', 'Bordeaux',
  'London', 'Manchester', 'Liverpool', 'Birmingham', 'Leeds', 'Glasgow', 'Edinburgh',
  'Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao', 'Málaga', 'Palma',
  'Rom', 'Mailand', 'Venedig', 'Florenz', 'Bologna', 'Palermo', 'Genua', 'Turin',
  'Amsterdam', 'Rotterdam', 'Amsterdam', 'Utrecht', 'Groningen', 'Arnheim',
  'Wien', 'Salzburg', 'Innsbruck', 'Linz', 'Graz', 'Klagenfurt',
  'Zürich', 'Genf', 'Basel', 'Bern', 'Lausanne', 'Luzern', 'St. Gallen',
  'Prag', 'Brünn', 'Ostrava', 'Pilsen', 'Olomouc', 'Liberec',
  'Budapest', 'Debrecen', 'Miskolc', 'Győr', 'Pécs', 'Szeged',
  'Warschau', 'Krakau', 'Wrocław', 'Posen', 'Danzig', 'Szczecin',
  'Bukarest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Brașov',
  'Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Pleven',
  'Athen', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Rethymno',
  'Lissabon', 'Porto', 'Covilhã', 'Funchal', 'Ponta Delgada', 'Madeira',
  'Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Kristiansand', 'Bodø',
  'Stockholm', 'Göteborg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro',
  'Helsinki', 'Tampere', 'Turku', 'Oulu', 'Jyväskylä', 'Lahti',
  'Kopenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Frederiksberg', 'Randers',
  'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia',
  'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville',
  'Toronto', 'Montréal', 'Vancouver', 'Calgary', 'Ottawa', 'Edmonton',
  'Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Hobart',
  'Tokio', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Sapporo',
  'Peking', 'Shanghai', 'Kanton', 'Shenzhen', 'Chongqing', 'Xi\'an',
  'Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata',
  'Bangkok', 'Phuket', 'Chiang Mai', 'Pattaya', 'Koh Samui', 'Hua Hin',
  'Ho-Chi-Minh-Stadt', 'Hanoi', 'Da Nang', 'Hoi An', 'Can Tho', 'Haiphong',
  'Jakarta', 'Surabaya', 'Medan', 'Makassar', 'Palembang', 'Semarang',
  'Manila', 'Cebu', 'Davao', 'Cagayan de Oro', 'Iloilo', 'Zamboanga',
  'Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju',
  'Singapur', 'Johor Bahru', 'George Town', 'Kuala Lumpur', 'Penang', 'Ipoh',
  'Kairo', 'Alexandria', 'Giza', 'Assiut', 'Luxor', 'Assuan',
  'Johannesburg', 'Kapstadt', 'Durban', 'Pretoria', 'Bloemfontein', 'Port Elizabeth',
  'Lagos', 'Abuja', 'Kano', 'Ibadan', 'Portharcourt', 'Enugu',
  'Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika',
  'Dar es Salaam', 'Dodoma', 'Mbeya', 'Arusha', 'Mwanza', 'Iringa',
  'São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte',
  'Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Tucumán',
  'Santiago', 'Valparaíso', 'Concepción', 'Valdivia', 'Puerto Montt', 'La Serena',
  'Lima', 'Arequipa', 'Trujillo', 'Callao', 'Cusco', 'Iquitos',
  'Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Santa Marta',
  'Mexico City', 'Guadalajara', 'Monterrey', 'Cancún', 'Playa del Carmen', 'Puerto Vallarta',

  // Sport Gegenstände
  'Fußball', 'Basketball', 'Volleyball', 'Handball', 'Tennis', 'Badminton', 'Tischtennisball',
  'Cricket-Ball', 'Baseball', 'Softball', 'Golf-Ball', 'Putter', 'Eishockey-Puck', 'Schläger',
  'Tennisschläger', 'Badmintonschläger', 'Baseball-Schläger', 'Hockey-Schläger', 'Golfschläger',
  'Raquette', 'Paddel', 'Schuh', 'Stiefel', 'Skischuh', 'Eislaufschuh', 'Rollschuh',
  'Helm', 'Schutzausrüstung', 'Schienbeinschoner', 'Ellbogenschoner', 'Handgelenk-Schutz',
  'Stöcke', 'Stange', 'Trampolin', 'Barren', 'Reck', 'Pferd', 'Schwebebalken',
  'Sprungbrett', 'Sprungplattform', 'Netz', 'Tor', 'Pfosten', 'Querlatte', 'Eckfahne',

  // Kleidung
  'Hemd', 'T-Shirt', 'Pullover', 'Pulli', 'Sweater', 'Hoodie', 'Jacke', 'Mantel', 'Weste',
  'Hose', 'Jeans', 'Shorts', 'Rock', 'Kleid', 'Anzug', 'Sakko', 'Smoking', 'Krawatte',
  'Fliege', 'Schal', 'Tuch', 'Gürtel', 'Strümpfe', 'Socken', 'Unterwäsche', 'BH', 'Slip',
  'Handschuhe', 'Mütze', 'Hut', 'Kappe', 'Baseballkappe', 'Bommelmütze', 'Stirnband',
  'Schal', 'Tuch', 'Überschuh', 'Galoschen', 'Gummistiefel', 'Wanderschuhe', 'Turnschuhe',
  'Laufschuhe', 'Sportschuhe', 'Fußballschuhe', 'Basketballschuhe', 'Tennisschuhe',
  'Sandale', 'Zehensandale', 'Flip-Flop', 'Pantoffel', 'Hausschuh', 'Slipper',
  'Anzug', 'Kostüm', 'Blazer', 'Sakko', 'Hose', 'Kammgarn', 'Worsted', 'Tweed',
  'Tailleur', 'Kostüm', 'Maßanzug', 'Konfektionsanzug', 'Ready-to-Wear', 'Haute Couture',

  // Möbel
  'Bett', 'Couch', 'Sofa', 'Sessel', 'Stuhl', 'Hocker', 'Tisch', 'Schreibtisch',
  'Kommode', 'Schrank', 'Kleiderschrank', 'Regal', 'Bücherregal', 'Vitrine', 'Anrichte',
  'Sideboard', 'Buffet', 'Schublade', 'Truhe', 'Kiste', 'Box', 'Container', 'Behälter',

  // Musik & Instrumente
  'Gitarre', 'Akustikgitarre', 'E-Gitarre', 'Bass', 'Klavier', 'Flügel', 'Synthesizer',
  'Orgel', 'Harmonium', 'Akkordeon', 'Geige', 'Violine', 'Cello', 'Kontrabass',
  'Vibraphone', 'Xylophon', 'Marimba', 'Glockenspiel', 'Becken', 'Gong', 'Trommeln',
  'Pauke', 'Tamburin', 'Maracas', 'Kastagnietten', 'Triangel', 'Rassel', 'Metall-Gefühl',
  'Trompete', 'Posaune', 'Horn', 'Tuba', 'Saxophon', 'Klarinette', 'Oboe', 'Fagott',
  'Flöte', 'Piccolo-Flöte', 'Blockflöte', 'Querflöte', 'Panflöte', 'Mundharmonika',
  'Mundstück', 'Ventil', 'Schallstück', 'Druckplatte', 'Saite', 'Bund', 'Steg',
  'Stimmwirbel', 'Griffbrett', 'Resonanzboden', 'Holz', 'Stoff', 'Metall', 'Kunststoff',
  'Schalloch', 'F-Loch', 'Loch', 'Taste', 'Pedal', 'Hebelwerk', 'Mechanik', 'Getriebe',

  // Körperteile
  'Kopf', 'Gehirn', 'Gesicht', 'Stirn', 'Schädel', 'Schläfe', 'Ohr', 'Auge', 'Augenbraue',
  'Wimpern', 'Augenlid', 'Nase', 'Nasenloch', 'Nasenseptum', 'Mund', 'Lippe', 'Zahn',
  'Zunge', 'Mandel', 'Zahfleisch', 'Backenzahn', 'Schneidezahn', 'Reißzahn', 'Weisheitszahn',
  'Kinn', 'Wange', 'Backe', 'Hals', 'Kehle', 'Kehlkopf', 'Stimmbänder', 'Speiseröhre',
  'Schulter', 'Oberarm', 'Unterarm', 'Ellbogen', 'Ellenbogenbeuger', 'Armmuskel', 'Bizeps',
  'Trizeps', 'Unterarmmuskel', 'Handfläche', 'Handrücken', 'Handgelenk', 'Finger', 'Daumen',
  'Zeigefinger', 'Mittelfinger', 'Ringfinger', 'kleiner Finger', 'Fingernagel', 'Nagelbett',
  'Brust', 'Brustkorb', 'Rippe', 'Lunge', 'Herz', 'Myokard', 'Perikard', 'Aorta',
  'Bauch', 'Bauchmuskeln', 'Leber', 'Niere', 'Milz', 'Bauchspeicheldrüse', 'Darm',
  'Dickdarm', 'Dünndarm', 'Magen', 'Speiseröhre', 'After', 'Blase', 'Harnleiter', 'Harnröhre',
  'Rücken', 'Wirbelsäule', 'Wirbel', 'Bandscheibe', 'Rückenmuskel', 'Lendenmuskeln',
  'Gesäß', 'Hüfte', 'Hüftknochen', 'Oberschenkel', 'Oberschenkelmuskel', 'Quadrizeps',
  'Kniesehne', 'Hamstring', 'Knie', 'Unterschenkel', 'Schienbein', 'Wadenbein', 'Waden',
  'Unterschenkelmuskel', 'Ferse', 'Fuss', 'Fußsohle', 'Fußrücken', 'Zehe', 'Großzehe',
  'Zeigezehe', 'Mittelzehe', 'Goldfinger', 'kleine Zehe', 'Zehennagel', 'Sprunggelenk',
  'Achillessehne', 'Fußgewölbe', 'Außenrand', 'Innenrand', 'Haut', 'Epidermis', 'Dermis',
  'Unterhaut', 'Falte', 'Furche', 'Muttermale', 'Leberfleck', 'Muttermal', 'Warze',
  'Hasenscharte', 'Sommerspross', 'Grübchen', 'Delle', 'Narbe', 'Kratzer', 'Schürfwunde',
  'Blut', 'Blutplättchen', 'rote Blutkörperchen', 'weiße Blutkörperchen', 'Leukozyten', 'Erythrozyten',
  'Knochen', 'Knorpel', 'Knochenmark', 'Knochenhaut', 'Sehnen', 'Bänder', 'Muskeln',

  // Abstraktionen
  'Liebe', 'Hass', 'Freude', 'Trauer', 'Angst', 'Hoffnung', 'Glauben', 'Zweifel',
  'Vertrauen', 'Misstrauen', 'Mut', 'Feigheit', 'Großzügigkeit', 'Geiz', 'Neid',
  'Eifersucht', 'Stolz', 'Demut', 'Scham', 'Reue', 'Vergebung', 'Dankbarkeit',
  'Zeit', 'Raum', 'Bewegung', 'Kraft', 'Energie', 'Materie', 'Temperatur',
  'Licht', 'Schatten', 'Farbe', 'Ton', 'Lärm', 'Stille', 'Echo', 'Widerhall',
  'Gedanke', 'Erinnerung', 'Traum', 'Alptraum', 'Illusion', 'Realität', 'Wahrheit',
  'Lüge', 'Geheimnis', 'Versprechen', 'Vertrag', 'Pflicht', 'Recht', 'Gesetz',
  'Freiheit', 'Versklavung', 'Sklaverei', 'Unabhängigkeit', 'Abhängigkeit', 'Autonomie',
  'Chaos', 'Ordnung', 'Struktur', 'System', 'Methode', 'Prozess', 'Ergebnis',
  'Ursache', 'Wirkung', 'Grund', 'Ziel', 'Zweck', 'Sinn', 'Bedeutung', 'Wichtigkeit',
  'Wert', 'Preis', 'Kosten', 'Gewinn', 'Verlust', 'Nutzen', 'Schaden', 'Vorteil',
  'Nachteil', 'Risiko', 'Chance', 'Möglichkeit', 'Unmöglichkeit', 'Sicherheit', 'Unsicherheit',
  'Erfolg', 'Misserfolg', 'Sieg', 'Niederlage', 'Gewinn', 'Verlust', 'Fortschritt', 'Rückschritt',
  'Eintönigkeit', 'Spannung', 'Nervenkitzel', 'Langeweile', 'Langeweile', 'Frustration', 'Zufriedenheit',
  'Glück', 'Unglück', 'Schicksal', 'Zufall', 'Schicksal', 'Vorherbestimmung', 'Freiheit',
  'Bestimmung', 'Pflicht', 'Ehre', 'Schande', 'Ruf', 'Ansehen', 'Status', 'Rang',
  'Titel', 'Name', 'Identität', 'Persönlichkeit', 'Charakter', 'Temperament', 'Wesensart',

  // Wissenschaft & Natur
  'Atom', 'Molekül', 'Ion', 'Elektron', 'Proton', 'Neutron', 'Quark', 'Photon',
  'Energie', 'Kraft', 'Beschleunigung', 'Geschwindigkeit', 'Impuls', 'Drehmoment', 'Leistung',
  'Arbeit', 'Wärmemenge', 'Strom', 'Spannung', 'Widerstand', 'Kapazität', 'Induktivität',
  'Magnetismus', 'Magnetfeld', 'Elektromagnetismus', 'Strahlung', 'Radioaktivität', 'Kernreaktion',
  'Kernfusion', 'Kernspaltung', 'Kettenreaktion', 'Explosion', 'Implosion', 'Kollaps',
  'Dichte', 'Druck', 'Volumen', 'Gewicht', 'Masse', 'Trägheit', 'Gravitation',
  'Anziehung', 'Abstoßung', 'Reibung', 'Auftrieb', 'Auftriebskraft', 'Auftriebskoeffizient',
  'Viskosität', 'Oberflächenspannung', 'Kapillarität', 'Kohäsion', 'Adhäsion', 'Osmose',
  'Diffusion', 'Lösung', 'Emulsion', 'Suspension', 'Kolloid', 'Gel', 'Sol',
  'Kristall', 'Mineral', 'Gestein', 'Sediment', 'Magma', 'Lava', 'Vulkan',
  'Erdbeben', 'Tsunami', 'Orkan', 'Tornado', 'Taifun', 'Zyklon', 'Antizyklon',
  'Hochdruck', 'Tiefdruckgebiet', 'Front', 'Wetterfronten', 'Kalt', 'Warmfront',
  'Evolution', 'Selektion', 'Anpassung', 'Mutation', 'Variation', 'Art', 'Gattung',
  'Familie', 'Ordnung', 'Klasse', 'Stamm', 'Reich', 'Reich', 'Unterreich',
  'Vermehrung', 'Fortpflanzung', 'Geschlechtsverkehr', 'Paarung', 'Befruchtung', 'Fertilisierung',
  'Keimung', 'Embryo', 'Fötus', 'Larve', 'Puppe', 'Metamorphose', 'Transformation',
  'Photosynthese', 'Atmen', 'Atmung', 'Gärung', 'Fermentation', 'Chemische Reaktion',
  'Verbrennung', 'Oxidation', 'Reduktion', 'Säure', 'Base', 'Salz', 'Neutraisierung',
  'pH-Wert', 'Puffer', 'Osmotischer Druck', 'Turgor', 'Plasmoyse', 'Hämolyse',
  'Metabolism', 'Anabolismus', 'Katabolismus', 'Enzym', 'Katalysator', 'Vitamin', 'Mineralstoff',
  'Hormon', 'Neurotransmitter', 'Antikörper', 'Antigen', 'Allergie', 'Immunreaktion',
  'Symptom', 'Syndrom', 'Pathologie', 'Infektion', 'Virus', 'Bakterium', 'Pilz',
  'Parasit', 'Wurm', 'Protozoon', 'Alge', 'Moose', 'Farn', 'Blütenpflanze',

  // Weitere Kategorien
  'Mathematik', 'Geometrie', 'Algebra', 'Kalkül', 'Statistik', 'Wahrscheinlichkeit',
  'Geschichte', 'Vorgeschichte', 'Antike', 'Mittelalter', 'Renaissance', 'Aufklärung',
  'Industrielle Revolution', 'Moderne', 'Romantik', 'Klassik', 'Neoklassik', 'Barock',
  'Archäologie', 'Anthropologie', 'Ethnologie', 'Soziologie', 'Psychologie', 'Philosophie',
  'Ethik', 'Ästhetik', 'Logik', 'Metaphysik', 'Epistemologie', 'Ontologie', 'Theologie',
  'Religion', 'Glaube', 'Dogma', 'Ritual', 'Gebet', 'Opfer', 'Segen', 'Fluch',
  'Magie', 'Hexerei', 'Zauberei', 'Hokuspokus', 'Trickery', 'Illusion', 'Täuschung',
  'Kunst', 'Malerei', 'Bildhauerei', 'Bildende Kunst', 'Grafik', 'Kalligraphie',
  'Literatur', 'Poesie', 'Drama', 'Roman', 'Novelle', 'Kurzgeschichte', 'Essay',
  'Kritik', 'Satire', 'Ironie', 'Humor', 'Witz', 'Komödie', 'Tragödie', 'Melodram',
  'Film', 'Kino', 'Fernsehen', 'Rundfunk', 'Radio', 'Podcast', 'Webcast', 'Streaming',
  'Musik', 'Klassik', 'Jazz', 'Blues', 'Rock', 'Pop', 'Hip-Hop', 'Reggae',
  'Country', 'Folk', 'Electronic', 'Elektronische Musik', 'Dance', 'House', 'Techno',
  'Trance', 'Dubstep', 'Metal', 'Punk', 'Alternative', 'Indie', 'Grunge', 'Emo',
  'Oper', 'Operette', 'Musical', 'Ballett', 'Modern Dance', 'Zeitgenössischer Tanz',
  'Schauspiel', 'Komödie', 'Tragödie', 'Melodrama', 'Farce', 'Slapstick', 'Pantomime',
  'Zirkus', 'Akrobatik', 'Jonglage', 'Magie', 'Zauberkunst', 'Prestidigitation',
  'Kuchen', 'Torten', 'Kekse', 'Bonbons', 'Schokolade', 'Taffy', 'Lutscher',
  'Eiscreme', 'Eis', 'Gefrorenes', 'Sorbet', 'Granita', 'Gelateria', 'Milkshake',
  'Pudding', 'Creme', 'Mousse', 'Soufflé', 'Meringue', 'Pavlova', 'Tiramisu',
  'Cheesecake', 'Brownies', 'Blondies', 'Muffins', 'Cupcakes', 'Donuts', 'Croissants',
  'Bagels', 'Brötchen', 'Brot', 'Weißbrot', 'Vollkornbrot', 'Sauerteig', 'Fladenbrot',
  'Flatbread', 'Naanbrot', 'Pita', 'Tortilla', 'Wrap', 'Panettone', 'Focaccia',
];

export function getRandomWord(): string {
  return WORDS[Math.floor(Math.random() * WORDS.length)];
}
